services:
  soloslack:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./database/soloslack.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 